version: '3'
services:
  app:
    container_name: vfv-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      -mongo
    mongo:
      container_name: vfvDb
      image: vfv-api
      ports:
        - '27017:27017'