kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: vfv
      role: api
  replicas: 1
  template:
    metadata:
      name: api-deployment
      labels:
        app: vfv
        role: api
        env: staging
    spec:
      containers:
      - name: node-app
        image: gcr.io/th-fnote/vfv:1.0.0
        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGODB_URL
         # - name: API_URL
          #  valueFrom:
          #    secretKeyRef:
          #      name: lesvault
           #     key: api_url_staging
          - name: NODE_ENV
            value: production
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        args: ['--env="HOST_IP=$(HOST_IP)"','--env="API_URL=$(API_URL)"','--env="MONGODB_URL=$(MONGODB_URL)"']
        ports:
        - name: payments
          containerPort: 3000